# Throat pruning experiment

What happens to `tau_sq_c`, `C_c`, `effective_conductance`, etc. if we remove "problematic" throats from a pore network, recompute Berg effective geometry (volumes/lengths/areas/coordination numbers), and re-solve?

Everything you'd normally tune lives in **Cell 3 (config)** and **Cell 4 (criterion)** below. You shouldn't need to open `analysis/artificial/throat_removal.py` again unless you want a rule that doesn't fit the `rank_criterion(...)` / plain-function patterns shown here.

Available throat-table columns to build criteria from (see `result["throat_table"].columns` for the full list):

| column | meaning |
|---|---|
| `C` | constriction ratio, `r_throat / min(r_body1, r_body2)` |
| `C_geomean` | constriction ratio, `r_throat / sqrt(r_body1 * r_body2)` (narrow relative to *both* neighbours) |
| `f` | fraction of total network current carried by the throat |
| `G` | throat conductance |
| `R1`, `R_throat`, `R2`, `R_edge` | series resistances (body1 segment, throat channel, body2 segment, total) |
| `P_edge_frac` | share of total dissipated power in the *whole* body1-throat-body2 segment (I^2 * R_edge) |
| `P_throat_only_frac` | share of total dissipated power in the throat channel *alone* (I^2 * R_throat) |
| `z_body1`, `z_body2` | coordination number of each endpoint body |
| `throat_id` | the id to map back to `network.throats` |

In [1]:
# Cell 1 -- imports & path setup (run once)
import sys
from pathlib import Path

import numpy as np
import pandas as pd

REPO_ROOT = Path.cwd().resolve().parent.parent  # analysis/notebooks -> analysis -> repo root
sys.path.insert(0, str(REPO_ROOT / "analysis" / "artificial"))

from throat_removal import prune_and_recompute, rank_criterion

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 160)

In [2]:
# Cell 2 -- load a microstructure's raw arrays
# (this recomputes the network from scratch, not the cached berg_cc result --
#  throat removal needs the actual PoreNetwork object, not just cached metrics)
MS_NAME = "microstructure1"
ms_dir = REPO_ROOT / "data" / MS_NAME

body_array = np.load(ms_dir / "body_array.npy")
segmented = np.load(ms_dir / "segmented.npy")

print(f"{MS_NAME}: body_array {body_array.shape}, {body_array.max()} bodies")

microstructure1: body_array (96, 96, 96), 404 bodies

In [3]:
# Cell 3 -- config
# Must match the cached berg_cc config for this microstructure, e.g.
# data/<ms_name>/version*/berg_cc/config.json, so results stay comparable
# to the pipeline's baseline numbers.
config = {
    "min_throat_size": 5,
    "direction": "x",
    "surface_axis": 0,
    "phase_id": 3,
    # optional, all have sensible defaults if omitted:
    # "dilate_both": True, "skip_surface_surface": True,
    # "area_method": "vox_projection", "alpha": 0.5, "split_volume_equal": True,
    # "sigma": 1.0, "delta_V": 1.0, "voxel_size": 1.0, "streamtube_method": "greedy_fast",
}

In [4]:
# Cell 4 -- criterion: pick ONE of the examples below (uncomment it), or write your own.
# A criterion is anything that takes the throat table (a pandas DataFrame) and
# returns a boolean array/Series -- True = remove this throat.

# --- Option A: the default "bottleneck" overlap (equivalent to criterion="bottleneck") ---
# bottom 10% of C_geomean AND top 10% of P_throat_only_frac -- gives 7 throats on microstructure1
# criterion = rank_criterion(
#     "C_geomean", 15, "bottom",
#     "P_throat_only_frac", 15, "top",
#     combine="and",
# )

# --- Option B: single-column, e.g. just the narrowest 5% of throats (pure geometry) ---
criterion = rank_criterion("C", percentile=5, tail="bottom")

# --- Option C: single-column, e.g. just the top 10% of I^2*R_edge dissipators ---
# criterion = rank_criterion("P_edge_frac", percentile=10, tail="top")

# --- Option D: overlap with OR instead of AND ---
# criterion = rank_criterion("C", 10, "bottom", "P_edge_frac", 10, "top", combine="or")

# --- Option E: write your own rule directly -- any function(df) -> bool array works ---
# def criterion(df):
#     return (df["C"] < 0.5) & (df["z_body1"] <= 3) & (df["z_body2"] <= 3)

# --- Option F: fixed count instead of a percentile (e.g. exactly the 20 narrowest) ---
# def criterion(df):
#     ids = df.nsmallest(20, "C_geomean")["throat_id"]
#     return df["throat_id"].isin(ids)

In [5]:
# Cell 5 -- run it
result = prune_and_recompute(body_array, segmented, config, criterion=criterion, verbose=False)

print("n_throats_removed:", result["n_throats_removed"])
print("n_bodies_newly_isolated:", result["n_bodies_newly_isolated"])
print("solve_failed:", result["solve_failed"])

if result["solve_failed"] is not None:
    print("\nThe removed throats disconnected inlet from outlet somewhere -- "
          "result['pruned'] is None. Try a smaller/looser criterion.")

[build_network_arrays] 290 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 658 throats indexed.
Current threshold I_threshold = 5.432e-11

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

[build_network_arrays] 270 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 625 throats indexed.
Current threshold I_threshold = 5.825e-11
n_throats_removed: 33
n_bodies_newly_isolated: 2
solve_failed: None

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

In [6]:
# Cell 6 -- baseline vs. pruned metrics side by side
if result["pruned"] is not None:
    comparison = (
        pd.Series(result["baseline"]).to_frame("baseline")
        .join(pd.Series(result["pruned"]).to_frame("pruned"))
        .join(pd.Series(result["delta"]).to_frame("delta"))
    )
    display(comparison)

                            baseline         pruned        delta
n_bodies                  404.000000     404.000000     0.000000
n_throats                 658.000000     625.000000   -33.000000
n_streamtubes             340.000000     308.000000   -32.000000
n_fallback_throats        290.000000     270.000000   -20.000000
Omega                  339307.000000  338817.000000  -490.000000
Omega_c                316824.066667  315703.888095 -1120.178571
V_stuck_total               0.000000       0.000000     0.000000
iota_sq_g                   0.227719       0.231454     0.003735
iota_sq_c                   0.243879       0.248399     0.004521
tau_sq_c                    0.379481       0.379877     0.000396
C_c                         1.556023       1.529301    -0.026722
consistency                 0.243879       0.248399     0.004521
phi_total                   0.383512       0.382958    -0.000554
phi_c                       0.358100       0.356834    -0.001266
F_total                    11.450429      11.281936    -0.168492
F_c                        11.450429      11.281936    -0.168492
total_current               8.383965       8.509178     0.125212
effective_conductance       8.383965       8.509178     0.125212
inv_tau_sq_c                2.635180       2.632430    -0.002749
inv_C_c                     0.642664       0.653893     0.011229
inv_F_c                     0.087333       0.088637     0.001304

In [7]:
# Cell 7 -- which throats got removed, and the full classification table
print("removed throat_ids:", sorted(result["removed_throat_ids"].tolist()))

result["throat_table"].loc[
    result["throat_table"]["throat_id"].isin(result["removed_throat_ids"]),
    ["throat_id", "body1", "body2", "C", "C_geomean", "f", "G",
     "P_edge_frac", "P_throat_only_frac", "z_body1", "z_body2"],
]

removed throat_ids: [1, 5, 123, 142, 145, 146, 171, 175, 188, 236, 271, 290, 296, 362, 379, 425, 432, 446, 448, 452, 461, 464, 512, 515, 521, 537, 553, 593, 605, 621, 626, 632, 644]

     throat_id  body1  body2         C  C_geomean             f         G   P_edge_frac  P_throat_only_frac  z_body1  z_body2
0            1      2     69  0.258199   0.233309  6.381511e-03  0.926411  3.685470e-04        4.980262e-04        3        7
4            5      5     77  0.267261   0.205567  1.106192e-02  0.981371  1.045388e-03        1.650107e-03        1        8
122        123     85    135  0.144338   0.132301  1.517162e-02  0.499999  3.859620e-03        6.281770e-03        6        8
141        142     96    113  0.277350   0.272259  3.837297e-03  0.869467  1.419866e-04        1.174136e-04        5        5
144        145     98    110  0.250000   0.250000  7.489817e-04  1.178440  3.991025e-06        5.948720e-06        6        7
145        146     98    121  0.218218   0.196407  2.586857e-03  1.299243  4.318211e-05        6.188767e-05        6        5
170        171    108    145  0.267261   0.211053  2.350509e-02  1.800676  2.572396e-03        3.551333e-03        3        5
174        175    109    169  0.267261   0.247617  9.590471e-03  0.708052  1.089091e-03        1.643995e-03        7        5
187        188    118    155  0.232495   0.212518  1.862326e-02  0.929916  3.126924e-03        4.745340e-03        6        5
235        236    142    163  0.182574   0.182574  1.493187e-02  0.912856  2.047744e-03        3.287119e-03        5        6
270        271    158    181  0.204124   0.189959  5.897586e-07  1.338916  2.177933e-12        3.146496e-12        7        5
289        290    167    172  0.242536   0.194622  9.886062e-03  1.271412  6.444803e-04        1.006136e-03        7        4
295        296    168    179  0.262613   0.254265  3.379498e-03  1.556660  6.151204e-05        8.827048e-05        6        5
361        362    203    210  0.277350   0.272259  2.290006e-17  1.729322  2.542417e-33        3.786863e-33        4        2
378        379    209    261  0.267261   0.267261  1.195260e-02  0.563287  2.126398e-03        2.970243e-03        7        6
424        425    236    259  0.267261   0.254598  6.767425e-03  0.757332  5.070025e-04        6.601513e-04        8       10
431        432    237    272  0.242536   0.222503  1.344979e-04  1.066647  1.421870e-07        2.105984e-07        6        7
445        446    246    260  0.235702   0.215000  4.034398e-03  1.685622  8.095557e-05        1.267593e-04        7        3
447        448    246    287  0.267261   0.250986  1.105644e-02  1.230005  8.332460e-04        1.048464e-03        7        5
451        452    247    299  0.166667   0.164429  2.889373e-02  1.898678  3.686423e-03        4.927508e-03        8       11
460        461    252    293  0.196116   0.180793  1.088469e-02  0.641983  1.547242e-03        2.405338e-03        7        7
463        464    254    258  0.200000   0.191089  1.181267e-02  1.757295  6.657347e-04        9.794773e-04        8        3
511        512    276    339  0.292770   0.286812  9.126019e-03  1.199198  5.822657e-04        8.078883e-04        7        8
514        515    278    284  0.277350   0.252247  3.868901e-03  0.910303  1.378602e-04        2.046131e-04        5        2
520        521    280    307  0.213201   0.208613  1.351840e-02  1.232218  1.243406e-03        1.629709e-03        6        4
536        537    290    312  0.229416   0.223747  3.238378e-03  1.246808  7.051878e-05        1.064661e-04        5        4
552        553    298    327  0.277350   0.231033  8.269393e-03  0.791646  7.242121e-04        1.077627e-03        6        5
592        593    321    338  0.229416   0.201384  4.342076e-03  1.283581  1.231462e-04        1.785032e-04        5        6
604        605    327    391  0.288675   0.282956  1.698657e-02  1.303182  1.856332e-03        2.563727e-03        5        1
620        621    338    378  0.277350   0.252247  3.679420e-03  1.087690  1.043525e-04        1.578722e-04        6        2
625        626    340    369  0.277350   0.255680  3.060273e-02  1.705239  4.604523e-03        6.162897e-03        4        2
631        632    342    381  0.242536   0.202475  1.591723e-02  1.471004  1.444012e-03        2.216429e-03        4        2
643        644    349    358  0.204124   0.202052  3.338644e-03  1.159978  8.056382e-05        1.220616e-04        4        3

## Sweeping / comparing multiple criteria

To compare several criteria at once, just loop and collect results -- each call re-solves independently, so no state leaks between runs.

In [8]:
# Cell 8 -- optional: compare several criteria in one table
criteria_to_try = {
    "bottleneck_default": rank_criterion("C_geomean", 10, "bottom", "P_throat_only_frac", 10, "top"),
    "bottom5pct_C": rank_criterion("C", 5, "bottom"),
    "top10pct_P_edge": rank_criterion("P_edge_frac", 10, "top"),
}

rows = []
for name, crit in criteria_to_try.items():
    r = prune_and_recompute(body_array, segmented, config, criterion=crit, verbose=False)
    row = {"criterion": name, "n_removed": r["n_throats_removed"], "solve_failed": r["solve_failed"] is not None}
    if r["pruned"] is not None:
        row.update({f"delta_{k}": v for k, v in r["delta"].items()
                    if k in ("tau_sq_c", "C_c", "effective_conductance", "phi_c", "Omega_c")})
    rows.append(row)

pd.DataFrame(rows)

[build_network_arrays] 290 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 658 throats indexed.
Current threshold I_threshold = 5.432e-11
[build_network_arrays] 286 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 651 throats indexed.

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)
/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

Current threshold I_threshold = 5.911e-11

[build_network_arrays] 290 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 658 throats indexed.
Current threshold I_threshold = 5.432e-11
[build_network_arrays] 270 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 625 throats indexed.

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

Current threshold I_threshold = 5.825e-11

[build_network_arrays] 290 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 658 throats indexed.
Current threshold I_threshold = 5.432e-11
[build_network_arrays] 239 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 592 throats indexed.

Current threshold I_threshold = 4.951e-11

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

            criterion  n_removed  solve_failed  delta_Omega_c  delta_tau_sq_c  delta_C_c  delta_phi_c  delta_effective_conductance
0  bottleneck_default          7         False    -349.866667       -0.001826   0.022932    -0.000395                    -0.170588
1        bottom5pct_C         33         False   -1120.178571        0.000396  -0.026722    -0.001266                     0.125212
2     top10pct_P_edge         66         False  -25757.047619       -0.172394   0.335820    -0.029113                    -4.926816

## Running on multiple microstructures

`data/` currently has two microstructures with the raw `body_array.npy` + a segmented volume that `prune_and_recompute` needs (it rebuilds the network from scratch, so cached `TRACE/*.csv` summaries alone aren't enough):

| microstructure | body_array shape | bodies | direction | surface_axis | segmented file |
|---|---|---|---|---|---|
| `microstructure1` | 96³ | 404 | `x` | `0` | `segmented.npy` |
| `Coarse_microstructure_0` | 150³ | 37 | `y` | `1` | `segmented_premesh.npy` |

(configs read from each microstructure's `data/<name>/version*/berg_cc/config.json` and `manifest.json` -- re-check those if you add a new microstructure, since `direction`/`surface_axis`/`segmented_file` differ per dataset.)

`run_on_microstructures(...)` runs `prune_and_recompute` once per microstructure with the *same* criterion and returns one tidy summary DataFrame (`baseline_<metric>`, `pruned_<metric>`, `delta_<metric>` columns) plus a dict of the full per-microstructure results for follow-up.

In [9]:
# Cell 9 -- define the microstructure set once (edit configs here if you add more)
from throat_removal import run_on_microstructures

microstructures = {
    "microstructure1": {
        "body_array": np.load(REPO_ROOT / "data" / "microstructure1" / "body_array.npy"),
        "segmented": np.load(REPO_ROOT / "data" / "microstructure1" / "segmented.npy"),
        "config": {"min_throat_size": 5, "direction": "x", "surface_axis": 0, "phase_id": 3},
    },
    "Coarse_microstructure_0": {
        "body_array": np.load(REPO_ROOT / "data" / "Coarse_microstructure_0" / "body_array.npy"),
        "segmented": np.load(REPO_ROOT / "data" / "Coarse_microstructure_0" / "segmented_premesh.npy"),
        "config": {"min_throat_size": 5, "direction": "y", "surface_axis": 1, "phase_id": 3},
    },
}

for name, ms in microstructures.items():
    print(f"{name}: body_array {ms['body_array'].shape}, {ms['body_array'].max()} bodies")

microstructure1: body_array (96, 96, 96), 404 bodies
Coarse_microstructure_0: body_array (150, 150, 150), 37 bodies

In [10]:
import json

microstructures = {}
for ms_dir in sorted((REPO_ROOT / "data").iterdir()):
    if not (ms_dir / "manifest.json").exists():
        continue  # skip loose files like YSZ_cleaned_x.npy
    manifest = json.loads((ms_dir / "manifest.json").read_text())
    seg_file = manifest.get("segmented_file", "segmented.npy")

    # find the latest berg_cc config actually used
    config_paths = sorted((ms_dir).glob("version*/berg_cc/config.json"))
    if not config_paths:
        continue
    berg_config = json.loads(config_paths[-1].read_text())

    microstructures[ms_dir.name] = {
        "body_array": np.load(ms_dir / "body_array.npy"),
        "segmented": np.load(ms_dir / seg_file),
        "config": {
            "min_throat_size": berg_config.get("min_throat_size", 5),
            "direction": berg_config.get("direction", "x"),
            "surface_axis": berg_config.get("surface_axis"),
            "phase_id": manifest.get("phase_id", 3),
        },
    }

for name, ms in microstructures.items():
    print(f"{name}: body_array {ms['body_array'].shape}, {ms['body_array'].max()} bodies")

Coarse_microstructure_0: body_array (150, 150, 150), 37 bodies
microstructure1: body_array (96, 96, 96), 404 bodies

In [11]:
# Cell 10 -- run the default criterion across all microstructures and collect results
from throat_removal import with_before_after_columns

summary_df, raw_results = run_on_microstructures(microstructures, criterion="bottleneck", verbose=False)

display_df = with_before_after_columns(
    summary_df, ["inv_tau_sq_c", "inv_C_c", "inv_F_c", "phi_c"]
)
display_df[[
    "ms_name", "solve_failed", "n_throats_removed", "n_bodies_newly_isolated",
    "inv_tau_sq_c_before/after", "inv_C_c_before/after", "inv_F_c_before/after", "phi_c_before/after",
]]

[build_network_arrays] 23 throat(s) used uniform-pipe fallback.
[build_network_arrays] 37 bodies, 47 throats indexed.
Current threshold I_threshold = 1.000e-10

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

[build_network_arrays] 23 throat(s) used uniform-pipe fallback.
[build_network_arrays] 37 bodies, 45 throats indexed.
Current threshold I_threshold = 1.000e-10

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

[build_network_arrays] 290 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 658 throats indexed.
Current threshold I_threshold = 5.432e-11
[build_network_arrays] 286 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 651 throats indexed.

Current threshold I_threshold = 5.911e-11

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

,ms_name,solve_failed,n_throats_removed,n_bodies_newly_isolated,inv_tau_sq_c_before/after,inv_C_c_before/after,inv_F_c_before/after,phi_c_before/after
0,Coarse_microstructure_0,False,2,0,2.752/2.921,0.5494/0.6002,0.008867/0.008788,0.04441/0.04277
1,microstructure1,False,7,0,2.635/2.648,0.6427/0.6333,0.08733/0.08556,0.3581/0.3577

In [12]:
# Cell 11 -- sweep a criterion across BOTH microstructures and multiple percentiles at once,
# to see whether a trend (e.g. "more removed -> worse tortuosity/constriction") holds
# consistently across datasets, not just one.
sweep_rows = []
for pct in [2, 5, 10, 15]:
    crit = rank_criterion("C_geomean", pct, "bottom", "P_throat_only_frac", pct, "top")
    df_pct, _ = run_on_microstructures(microstructures, criterion=crit, verbose=False)
    df_pct.insert(0, "percentile", pct)
    sweep_rows.append(df_pct)

sweep_df = pd.concat(sweep_rows, ignore_index=True)
sweep_display_df = with_before_after_columns(
    sweep_df, ["inv_tau_sq_c", "inv_C_c", "inv_F_c", "phi_c","effective_conductance"]
)
sweep_display_df[[
    "percentile", "ms_name", "solve_failed", "n_throats_removed",
    "inv_tau_sq_c_before/after", "inv_C_c_before/after", "inv_F_c_before/after", "phi_c_before/after",
]]

[build_network_arrays] 23 throat(s) used uniform-pipe fallback.
[build_network_arrays] 37 bodies, 47 throats indexed.
Current threshold I_threshold = 1.000e-10

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

[build_network_arrays] 23 throat(s) used uniform-pipe fallback.
[build_network_arrays] 37 bodies, 47 throats indexed.
Current threshold I_threshold = 1.000e-10

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

[build_network_arrays] 290 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 658 throats indexed.
Current threshold I_threshold = 5.432e-11
[build_network_arrays] 290 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 658 throats indexed.

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

Current threshold I_threshold = 5.432e-11

[build_network_arrays] 23 throat(s) used uniform-pipe fallback.
[build_network_arrays] 37 bodies, 47 throats indexed.
Current threshold I_threshold = 1.000e-10

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

[build_network_arrays] 23 throat(s) used uniform-pipe fallback.
[build_network_arrays] 37 bodies, 46 throats indexed.
Current threshold I_threshold = 1.000e-10

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

[build_network_arrays] 290 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 658 throats indexed.
Current threshold I_threshold = 5.432e-11

[build_network_arrays] 288 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 656 throats indexed.
Current threshold I_threshold = 5.402e-11

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

[build_network_arrays] 23 throat(s) used uniform-pipe fallback.
[build_network_arrays] 37 bodies, 47 throats indexed.
Current threshold I_threshold = 1.000e-10

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

[build_network_arrays] 23 throat(s) used uniform-pipe fallback.
[build_network_arrays] 37 bodies, 45 throats indexed.
Current threshold I_threshold = 1.000e-10

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

[build_network_arrays] 290 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 658 throats indexed.
Current threshold I_threshold = 5.432e-11
[build_network_arrays] 286 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 651 throats indexed.

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

Current threshold I_threshold = 5.911e-11

[build_network_arrays] 23 throat(s) used uniform-pipe fallback.
[build_network_arrays] 37 bodies, 47 throats indexed.
Current threshold I_threshold = 1.000e-10

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

[build_network_arrays] 23 throat(s) used uniform-pipe fallback.
[build_network_arrays] 37 bodies, 45 throats indexed.
Current threshold I_threshold = 1.000e-10

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

[build_network_arrays] 290 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 658 throats indexed.
Current threshold I_threshold = 5.432e-11
[build_network_arrays] 278 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 633 throats indexed.

Current threshold I_threshold = 5.982e-11

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

   percentile                  ms_name  solve_failed  n_throats_removed inv_tau_sq_c_before/after inv_C_c_before/after inv_F_c_before/after phi_c_before/after
0           2  Coarse_microstructure_0         False                  0               2.752/2.752        0.5494/0.5494    0.008867/0.008867    0.04441/0.04441
1           2          microstructure1         False                  0               2.635/2.635        0.6427/0.6427      0.08733/0.08733      0.3581/0.3581
2           5  Coarse_microstructure_0         False                  1               2.752/2.803         0.5494/0.559    0.008867/0.008768    0.04441/0.04397
3           5          microstructure1         False                  2               2.635/2.643        0.6427/0.6399       0.08733/0.0867      0.3581/0.3581
4          10  Coarse_microstructure_0         False                  2               2.752/2.921        0.5494/0.6002    0.008867/0.008788    0.04441/0.04277
5          10          microstructure1         False                  7               2.635/2.648        0.6427/0.6333      0.08733/0.08556      0.3581/0.3577
6          15  Coarse_microstructure_0         False                  2               2.752/2.921        0.5494/0.6002    0.008867/0.008788    0.04441/0.04277
7          15          microstructure1         False                 25               2.635/2.891        0.6427/0.6145      0.08733/0.07447      0.3581/0.3503

## Random removal as a control

Is the targeted "bottleneck" criterion actually worse than removing the *same number* of throats at random? `random_criterion(percentile, seed=...)` removes a uniformly random `percentile`% of throats (no geometry/current involved), so you can compare it directly against `rank_criterion(...)` at the same percentile. Since a single random draw can land on an unusually lucky/unlucky set, run several seeds and look at the spread, not just one.

In [13]:
# Cell 12 -- targeted vs. random removal, SAME throat COUNT, multiple random seeds.
# random_criterion(match=targeted_crit) runs targeted_crit once to count how many
# throats it selects, then draws that many throats at random -- an exact apples-to-
# apples comparison ("my rule removed K throats, here's a random K instead").
from throat_removal import random_criterion

N_SEEDS = 8

targeted_crit = rank_criterion("C_geomean", 10, "bottom", "P_throat_only_frac", 10, "top")

rows = []
r_targeted = prune_and_recompute(body_array, segmented, config, criterion=targeted_crit, verbose=False)
print(f"targeted criterion removed {r_targeted['n_throats_removed']} throats -- "
      f"matching random draws to this exact count")

rows.append({
    "kind": "targeted_bottleneck", "seed": None,
    "n_removed": r_targeted["n_throats_removed"], "solve_failed": r_targeted["solve_failed"] is not None,
    **({f"pruned_{k}": v for k, v in r_targeted["pruned"].items()} if r_targeted["pruned"] is not None else {}),
})

for seed in range(N_SEEDS):
    crit = random_criterion(match=targeted_crit, seed=seed)
    r = prune_and_recompute(body_array, segmented, config, criterion=crit, verbose=False)
    rows.append({
        "kind": "random", "seed": seed,
        "n_removed": r["n_throats_removed"], "solve_failed": r["solve_failed"] is not None,
        **({f"pruned_{k}": v for k, v in r["pruned"].items()} if r["pruned"] is not None else {}),
    })

control_df = pd.DataFrame(rows)
control_df[["kind", "seed", "n_removed", "solve_failed", "pruned_tau_sq_c", "pruned_C_c", "pruned_effective_conductance"]]

[build_network_arrays] 290 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 658 throats indexed.
Current threshold I_threshold = 5.432e-11
[build_network_arrays] 286 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 651 throats indexed.

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)
/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

Current threshold I_threshold = 5.911e-11
targeted criterion removed 7 throats -- matching random draws to this exact count

[build_network_arrays] 290 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 658 throats indexed.
Current threshold I_threshold = 5.432e-11
[build_network_arrays] 283 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 651 throats indexed.

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

Current threshold I_threshold = 5.429e-11

[build_network_arrays] 290 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 658 throats indexed.
Current threshold I_threshold = 5.432e-11

[build_network_arrays] 284 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 651 throats indexed.
Current threshold I_threshold = 5.501e-11

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

[build_network_arrays] 290 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 658 throats indexed.
Current threshold I_threshold = 5.432e-11
[build_network_arrays] 282 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 651 throats indexed.

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

Current threshold I_threshold = 5.500e-11

[build_network_arrays] 290 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 658 throats indexed.
Current threshold I_threshold = 5.432e-11
[build_network_arrays] 285 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 651 throats indexed.

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

Current threshold I_threshold = 5.421e-11

[build_network_arrays] 290 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 658 throats indexed.
Current threshold I_threshold = 5.432e-11
[build_network_arrays] 281 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 651 throats indexed.

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

Current threshold I_threshold = 5.340e-11

[build_network_arrays] 290 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 658 throats indexed.
Current threshold I_threshold = 5.432e-11
[build_network_arrays] 284 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 651 throats indexed.

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

Current threshold I_threshold = 5.260e-11

[build_network_arrays] 290 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 658 throats indexed.
Current threshold I_threshold = 5.432e-11

[build_network_arrays] 284 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 651 throats indexed.
Current threshold I_threshold = 5.438e-11

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

[build_network_arrays] 290 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 658 throats indexed.
Current threshold I_threshold = 5.432e-11
[build_network_arrays] 288 throat(s) used uniform-pipe fallback.
[build_network_arrays] 404 bodies, 651 throats indexed.

Current threshold I_threshold = 5.312e-11

/Users/rochan/miniconda3/envs/rbenv/lib/python3.10/site-packages/scipy/sparse/_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)

                  kind  seed  n_removed  solve_failed  pruned_tau_sq_c  pruned_C_c  pruned_effective_conductance
0  targeted_bottleneck   NaN          7         False         0.377655    1.578954                      8.213378
1               random   0.0          7         False         0.374836    1.550588                      8.264022
2               random   1.0          7         False         0.381756    1.553949                      8.397097
3               random   2.0          7         False         0.370682    1.582753                      8.006162
4               random   3.0          7         False         0.381874    1.564087                      8.325685
5               random   4.0          7         False         0.380399    1.576515                      8.216520
6               random   5.0          7         False         0.381211    1.564799                      8.360102
7               random   6.0          7         False         0.376698    1.557741                      8.312670
8               random   7.0          7         False         0.380576    1.576312                      8.270307